language: node_js
node_js:
  - "8"

services:
  - docker

before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t note-b-web .
  - docker tag note-b-web:latest gzfeng/note-b-web
  - docker push gzfeng/note-b-web:latest
  - docker ps -a

