language: node_js
node_js:
  - "8"

services:
  - docker


echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install:
  - docker build -t note-b-web .
  - docker ps -a
  - docker tag note-b-web:latest gzfeng/note-b-web
  - docker push "$DOCKER_USERNAME"/note-b-web:latest

