language: node_js
node_js:
  - "8"

services:
  - docker

install:
  - docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t note-b-web .
  - docker tag note-b-web:latest gzfeng/note-b-web
  - docker push "$DOCKER_USERNAME"/note-b-web:latest
  - docker ps -a

